name:                servant-kotlin
version:             0.1.1.9
synopsis:            Automatically derive Kotlin class to query servant webservices
description:         See README at <https://github.com/matsubara0507/servant-kotlin#readme>
homepage:            https://github.com/matsubara0507/servant-kotlin#readme
license:             MIT
author:              MATSUBARA Nobutada
maintainer:          MATSUBARA Nobutada
copyright:           2017-2018 MATSUBARA Nobutada
category:            Web
extra-source-files:
  - README.md

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - containers
  - directory
  - formatting
  - lens
  - servant
  - servant-foreign
  - text
  - time
  - wl-pprint-text

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - src
      - test
    dependencies:
      - aeson
      - hspec
      - http-api-data

benchmarks:
  generate-test:
    main: example/Generater.hs
    dependencies:
      - aeson
      - http-api-data
      - servant-kotlin
      - shelly
